// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoo0GYgP7UeAMRXoalq8X6XBtkbHSNj8Q',
    appId: '1:6060916194:web:b4bc5aa365cf7aeb364dbb',
    messagingSenderId: '6060916194',
    projectId: 'chat-app-8216a',
    authDomain: 'chat-app-8216a.firebaseapp.com',
    storageBucket: 'chat-app-8216a.appspot.com',
    measurementId: 'G-0P98B39D1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Mh4JQ2WLgkb6SooXoUgs7cLnJHd37Go',
    appId: '1:6060916194:android:1fc90b55175e21b3364dbb',
    messagingSenderId: '6060916194',
    projectId: 'chat-app-8216a',
    storageBucket: 'chat-app-8216a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0LWRpPwVZq_Ah8WPwYraP9wMYKjiq3-w',
    appId: '1:6060916194:ios:029d5973cb4bd486364dbb',
    messagingSenderId: '6060916194',
    projectId: 'chat-app-8216a',
    storageBucket: 'chat-app-8216a.appspot.com',
    iosClientId: '6060916194-b7saadv2fqnll1n86ofaulrbiu7q243j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0LWRpPwVZq_Ah8WPwYraP9wMYKjiq3-w',
    appId: '1:6060916194:ios:029d5973cb4bd486364dbb',
    messagingSenderId: '6060916194',
    projectId: 'chat-app-8216a',
    storageBucket: 'chat-app-8216a.appspot.com',
    iosClientId: '6060916194-b7saadv2fqnll1n86ofaulrbiu7q243j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
